version: '3'
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: library/postgres:15
    container_name: "keycloak_postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-net

  keycloak:
    image: bitnami/keycloak:22.0.5
    container_name: "keycloak_app"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
      KEYCLOAK_DATABASE_VENDER: POSTGRES
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOG_LEVEL: INFO
      KEYCLOAK_HTTP_PORT: 8090
#      KEYCLOAK_EXTRA_ARGS: "--import-realm"
      TZ: Asia/Tokyo
    volumes:
#      - ./keycloak-realm-export.json:/opt/bitnami/keycloak/data/import/realm-export.json
#      - ./providers/keycloak-template-1.0-SNAPSHOT.jar:/opt/bitnami/keycloak/providers/keycloak-template-1.0-SNAPSHOT.jar
      - ./themes/custom-theme:/opt/bitnami/keycloak/themes/custom-theme
#      - ./conf/keycloak.conf:/opt/bitnami/keycloak/conf/keycloak.conf
    ports:
      - 8090:8090
    depends_on:
      - postgres
      - maildev
    networks:
      - keycloak-net
  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - keycloak-net

networks:
  keycloak-net:
    driver: bridge
